# Generated by Django 4.1.5 on 2023-04-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='/images/default-avatar.png', max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_img',
            field=models.CharField(default='/images/default-cover_img.png', max_length=300),
        ),
    ]
