# Generated by Django 4.1.5 on 2023-03-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_token',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
