# Generated by Django 4.1.5 on 2023-03-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_secret_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret_token',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
