# Generated by Django 4.1.5 on 2023-04-03 00:15

from django.db import migrations, models
import django.db.models.deletion
import utilities.media_paths


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(default='profiles/avatar_default.png', upload_to=utilities.media_paths.avatar_path)),
                ('tag_text', models.CharField(max_length=100)),
                ('tag_symbol', models.CharField(default='#', max_length=1)),
                ('object_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
