# Generated by Django 4.1.5 on 2023-01-13 16:07

from django.db import migrations, models
import post.music_model
import post.picture_model
import post.utils
import post.video_model
import utilities.media_paths


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to=post.music_model.post_video_path, validators=[post.utils.validate_file])),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='default/photo.png', null=True, upload_to=post.picture_model.post_photo_path, validators=[post.utils.validate_file])),
                ('alt_text', models.CharField(default='post', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('key', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('publish', models.CharField(default='Public', max_length=35)),
                ('caption', models.CharField(blank=True, max_length=250, null=True)),
                ('excerpt', models.TextField(blank=True, max_length=2000, null=True)),
                ('hashtags', models.CharField(blank=True, max_length=250, null=True)),
                ('thumbnail', models.ImageField(blank=True, default='posts/default-thumbnail.png', null=True, upload_to=utilities.media_paths.post_thumbnail_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_rate', models.BigIntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ('-updated_at', 'activity_rate', '-created_at'),
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=post.video_model.post_video_path, validators=[post.utils.validate_file])),
                ('title', models.TextField(blank=True, max_length=150, null=True)),
                ('alt_text', models.CharField(default='post', max_length=50)),
                ('thumbnail', models.ImageField(blank=True, default='default/video.png', null=True, upload_to=utilities.media_paths.post_thumbnail_path)),
            ],
        ),
    ]
