# Generated by Django 4.1.5 on 2023-01-24 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.picture_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('key', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('publish', models.CharField(default='Public', max_length=35)),
                ('caption', models.CharField(blank=True, max_length=250, null=True)),
                ('excerpt', models.TextField(blank=True, max_length=2000, null=True)),
                ('hashtags', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_rate', models.BigIntegerField(blank=True, default=1, null=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photo.photo')),
                ('shares', models.ManyToManyField(blank=True, related_name='post_shares', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='tag', to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(blank=True, related_name='views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', 'activity_rate', '-created_at'),
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='default/photo.png', null=True, upload_to=post.picture_model.post_photo_path)),
                ('alt_text', models.CharField(default='post by', max_length=50)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
