# Generated by Django 4.1.5 on 2023-01-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='alt_text',
            field=models.CharField(default='post by', max_length=50),
        ),
    ]
