# Generated by Django 4.1.5 on 2023-01-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=1000)),
                ('delivered', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('last_msg', models.TextField(blank=True, max_length=1000, null=True)),
                ('last_msg_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
