# Generated by Django 4.1.5 on 2023-01-24 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('profile_type', models.CharField(default='Celebrity', editable=False, max_length=50)),
                ('friends', models.ManyToManyField(blank=True, related_name='celebrity_friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='celebrity_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Celebrity',
                'verbose_name_plural': 'Celebrities',
            },
        ),
    ]
