# Generated by Django 4.1.5 on 2023-04-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('profile_type', models.CharField(default='Administrator', editable=False, max_length=50)),
                ('is_premium', models.BooleanField(default=False)),
            ],
        ),
    ]
