# Generated by Django 4.1.5 on 2023-03-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('profile_type', models.CharField(blank=True, default='Supporter', editable=False, max_length=50)),
            ],
        ),
    ]
