# Generated by Django 4.1.5 on 2023-01-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('profile_type', models.CharField(blank=True, default='Supporter', editable=False, max_length=50)),
            ],
        ),
    ]
