# Generated by Django 4.1.5 on 2023-01-24 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utilities.media_paths


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('file', models.FileField(blank=True, null=True, upload_to=utilities.media_paths.comment_file_path)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=utilities.media_paths.comment_picture_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_updated', models.BooleanField(default=False)),
                ('activity_rate', models.BigIntegerField(blank=True, default=1, null=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comment.comment')),
            ],
            options={
                'ordering': ('-updated_at', 'activity_rate', '-created_at'),
            },
        ),
    ]
