# Generated by Django 4.1.5 on 2023-01-20 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-updated_at', 'activity_rate', '-created_at')},
        ),
    ]
