# Generated by Django 4.1.5 on 2023-03-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_for', models.CharField(choices=[('post', 'Post'), ('avatar', 'Avatar'), ('thumbnail', 'Thumbnail')], default='avatar', max_length=100)),
                ('author_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='author')),
                ('alt_text', models.CharField(default='post by', max_length=50)),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('width', models.IntegerField(default=120)),
                ('height', models.IntegerField(default=120)),
                ('file_url', models.CharField(default='https://firebasestorage.googleapis.com/v0/b/chatvite100.appspot.com/o/profiles%2Fcelesup%2Fprofiles-users%2Fdefault.jpg?alt=media&token=553f9506-abc6-47c6-ab28-989ca3815129', max_length=50)),
            ],
        ),
    ]
